### ISSUE TITLE
Training the autoencoder

### ISSUE THREAD

**Issue by rangchu** [iSarmad/RL-GAN-Net#3]
Hello thank you for providing this to accompany your work. 
Really cool stuff here.

I am trying to train the autoencoder and I encountered this error, I was  wondering what could be the solution
`ERROR:visdom:[Errno 111] Connection refused
Traceback (most recent call last):
  File "main2.py", line 484, in <module>
    main()
  File "main2.py", line 267, in main
    chamfer = ChamferLoss(args)
  File "/home/Documents/Git/RL-GAN-Net/models/lossess.py", line 201, in __init__
    self.res.setTempMemoryFraction(0.1)
  File "/home/anaconda3/envs/pytorch-venv/lib/python3.7/site-packages/faiss/swigfaiss.py", line 1195, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, StandardGpuResources, name)
  File "/home/paolo/anaconda3/envs/pytorch-venv/lib/python3.7/site-packages/faiss/swigfaiss.py", line 80, in _swig_getattr
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
AttributeError: 'StandardGpuResources' object has no attribute 'setTempMemoryFraction'`

**Comment by doudoulaile** [comment]
I solved this problem by commenting out this line of code

**Comment by rangchu** [comment]
> I solved this problem by commenting out this line of code.
> `# self.res.setTempMemoryFraction(0.1)`

That's great. Can I ask which file is this line of code located?

**Comment by doudoulaile** [comment]
lossess. py



---Original---

**Comment by rangchu** [comment]
> RL-GAN-Net/models/lossess.py, line 201
> […](#)
> ---Original--- From: "rangchu"<notifications@github.com> Date: Mon, Aug 26, 2019 15:36 PM To: "iSarmad/RL-GAN-Net"<RL-GAN-Net@noreply.github.com>; Cc: "doudoulaile"<2274570131@qq.com>;"Comment"<comment@noreply.github.com>; Subject: Re: [iSarmad/RL-GAN-Net] Training the autoencoder (#3) I solved this problem by commenting out this line of code. # self.res.setTempMemoryFraction(0.1) That's great. Can I ask which file is this line of code located? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.



> I solved this problem by commenting out this line of code.
> `# self.res.setTempMemoryFraction(0.1)`


Unfortunately, it didn't work for me, I got this error instead
`ERROR:visdom:[Errno 111] Connection refused`
`/home/myname/anaconda3/envs/rlgan-venv/lib/python3.7/site-packages/torch/optim/lr_scheduler.py:82: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule.See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
Traceback (most recent call last):
  File "main2.py", line 484, in <module>
    main()
  File "main2.py", line 285, in main
    train_loss, _, _ = train(train_loader,model,optimizer,epoch,args,chamfer,visualizer,train_writer)
  File "main2.py", line 444, in train
    loss_1 = chamfer(trans_input, pc_1) #
  File "/home/paolo/Documents/Git/RL-GAN-Net/models/lossess.py", line 297, in __call__
    loss = self.forward(predict_pc, gt_pc)
  File "/home/paolo/Documents/Git/RL-GAN-Net/models/lossess.py", line 256, in forward
    selected_gt_by_predict = selected_gt_by_predict.to(self.opt.device)
RuntimeError: CUDA error: invalid device ordinal
`

**Comment by rangchu** [comment]
> RL-GAN-Net/models/lossess.py, line 201
> […](#)
> ---Original--- From: "rangchu"<notifications@github.com> Date: Mon, Aug 26, 2019 15:36 PM To: "iSarmad/RL-GAN-Net"<RL-GAN-Net@noreply.github.com>; Cc: "doudoulaile"<2274570131@qq.com>;"Comment"<comment@noreply.github.com>; Subject: Re: [iSarmad/RL-GAN-Net] Training the autoencoder (#3) I solved this problem by commenting out this line of code. # self.res.setTempMemoryFraction(0.1) That's great. Can I ask which file is this line of code located? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

I switched from conda to pip environment just to try to make it work.
Did you encounter an error like this by chance?

> `ModuleNotFoundError: No module named '_swigfaiss'`

**Comment by rangchu** [comment]
> > RL-GAN-Net/models/lossess.py, line 201
> > […](#)
> > ---Original--- From: "rangchu"[notifications@github.com](mailto:notifications@github.com) Date: Mon, Aug 26, 2019 15:36 PM To: "iSarmad/RL-GAN-Net"[RL-GAN-Net@noreply.github.com](mailto:RL-GAN-Net@noreply.github.com); Cc: "doudoulaile"[2274570131@qq.com](mailto:2274570131@qq.com);"Comment"[comment@noreply.github.com](mailto:comment@noreply.github.com); Subject: Re: [iSarmad/RL-GAN-Net] Training the autoencoder (#3) I solved this problem by commenting out this line of code. # self.res.setTempMemoryFraction(0.1) That's great. Can I ask which file is this line of code located? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.
> 
> I switched from conda to pip environment just to try to make it work.
> Did you encounter an error like this by chance?
> 
> > `ModuleNotFoundError: No module named '_swigfaiss'`

I managed to solve this by switching  from pip environment to anaconda environment.
However I run to another issue
`  File "main2.py", line 487, in <module>
    main()
  File "main2.py", line 288, in main
    train_loss, _, _ = train(train_loader,model,optimizer,epoch,args,chamfer,visualizer,train_writer)
  File "main2.py", line 447, in train
    loss_1 = chamfer(trans_input, pc_1) #
  File "/home/user/Documents/Git/RL-GAN-Net/models/lossess.py", line 297, in __call__
    loss = self.forward(predict_pc, gt_pc)
  File "/home/user/Documents/Git/RL-GAN-Net/models/lossess.py", line 261, in forward
    index_predict = self.build_nn_index(predict_pc_np[i])
  File "/home/user/Documents/Git/RL-GAN-Net/models/lossess.py", line 216, in build_nn_index
    index = faiss.index_cpu_to_gpu(self.res, self.opt.gpu_id, index_cpu)
  File "/home/user/anaconda3/envs/rlgan-venv/lib/python3.7/site-packages/faiss/__init__.py", line 370, in replacement_function
    result = original_function(*args)
RuntimeError: Error in faiss::gpu::GpuIndex::GpuIndex(faiss::gpu::GpuResources*, int, faiss::MetricType, faiss::gpu::GpuIndexConfig) at gpu/GpuIndex.cu:48: Error: 'device_ < getNumDevices()' failed: Invalid GPU device 1
`

**Comment by rangchu** [comment]
> > RL-GAN-Net/models/lossess.py, line 201
> > […](#)
> > ---Original--- From: "rangchu"[notifications@github.com](mailto:notifications@github.com) Date: Mon, Aug 26, 2019 15:36 PM To: "iSarmad/RL-GAN-Net"[RL-GAN-Net@noreply.github.com](mailto:RL-GAN-Net@noreply.github.com); Cc: "doudoulaile"[2274570131@qq.com](mailto:2274570131@qq.com);"Comment"[comment@noreply.github.com](mailto:comment@noreply.github.com); Subject: Re: [iSarmad/RL-GAN-Net] Training the autoencoder (#3) I solved this problem by commenting out this line of code. # self.res.setTempMemoryFraction(0.1) That's great. Can I ask which file is this line of code located? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.
> 
> > I solved this problem by commenting out this line of code.
> > `# self.res.setTempMemoryFraction(0.1)`
> 
> Unfortunately, it didn't work for me, I got this error instead
> `ERROR:visdom:[Errno 111] Connection refused`
> `/home/myname/anaconda3/envs/rlgan-venv/lib/python3.7/site-packages/torch/optim/lr_scheduler.py:82: UserWarning: Detected call of `lr_scheduler.step()`before`optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()`before`lr_scheduler.step()`. Failure to do this will result in PyTorch skipping the first value of the learning rate schedule.See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning) Traceback (most recent call last): File "main2.py", line 484, in <module> main() File "main2.py", line 285, in main train_loss, _, _ = train(train_loader,model,optimizer,epoch,args,chamfer,visualizer,train_writer) File "main2.py", line 444, in train loss_1 = chamfer(trans_input, pc_1) # File "/home/myname/Documents/Git/RL-GAN-Net/models/lossess.py", line 297, in __call__ loss = self.forward(predict_pc, gt_pc) File "/home/myname/Documents/Git/RL-GAN-Net/models/lossess.py", line 256, in forward selected_gt_by_predict = selected_gt_by_predict.to(self.opt.device) RuntimeError: CUDA error: invalid device ordinal `

Silly me. I forgot to start the visdom server

**Comment by doudoulaile** [comment]
have you finished running the code?&nbsp;



---Original---
